### ISSUE TITLE
Add descriptions to Needfinding sections

### ISSUE THREAD

**Issue by JCayllahuaG** [upc-pre-202302-SI572-SW71-softtech/go2climb-docs#5]
**Tasks:**
- [ ] Add description to User Personas section.
- [ ] Add description to User Task Matrix section.
- [ ] Add description to User Journey Mapping section.
- [ ] Add description to Empathy mapping section.
- [ ] Add description to As-is Scenario Mapping section.
